apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cofreseguro.fullname" . }}-secrets
type: Opaque
stringData:
  jwtSecret: {{ .Values.jwtSecret | quote }}
{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cofreseguro.fullname" . }}-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
